/* c8 ignore start */
import type { Config } from 'prettier';
export const define = ({
  arrowParens = 'always',
  bracketSameLine = false,
  bracketSpacing = true,
  checkIgnorePragma = false,
  embeddedLanguageFormatting = 'auto',
  endOfLine = 'lf',
  experimentalOperatorPosition = 'start',
  experimentalTernaries = true,
  htmlWhitespaceSensitivity = 'css',
  insertPragma = false,
  jsxSingleQuote = true,
  objectWrap = 'collapse',
  overrides = [],
  printWidth = 80,
  proseWrap = 'always',
  quoteProps: quoteProperties = 'as-needed',
  rangeEnd = Infinity,
  rangeStart = 0,
  requirePragma = false,
  semi = true,
  singleAttributePerLine = false,
  singleQuote = true,
  tabWidth = 2,
  trailingComma = 'none',
  useTabs = false,
  vueIndentScriptAndStyle = false,
  ...rest
}: Config = {}): Config => ({
  arrowParens,
  bracketSameLine,
  bracketSpacing,
  checkIgnorePragma,
  embeddedLanguageFormatting,
  endOfLine,
  experimentalOperatorPosition,
  experimentalTernaries,
  htmlWhitespaceSensitivity,
  insertPragma,
  jsxSingleQuote,
  objectWrap,
  overrides,
  printWidth,
  proseWrap,
  quoteProps: quoteProperties,
  rangeEnd,
  rangeStart,
  requirePragma,
  semi,
  singleAttributePerLine,
  singleQuote,
  tabWidth,
  trailingComma,
  useTabs,
  vueIndentScriptAndStyle,
  ...rest
});
/* c8 ignore end */
