import type { SharedKeyword } from '../shared.js';
/**
 * https://developer.mozilla.org/en-US/docs/Glossary/Color_space
 *
 * https://www.w3.org/TR/css-color-4/#typedef-colorspace-params
 */
export type ColorSpace =
  /** https://www.w3.org/TR/css-color-4/#valdef-color-a98-rgb */
  | 'a98-rgb'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-display-p3 */
  | 'display-p3'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-prophoto-rgb */
  | 'prophoto-rgb'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-rec2020 */
  | 'rec2020'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-srgb-linear */
  | 'srgb-linear'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-srgb */
  | 'srgb'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-xyz-d50 */
  | 'xyz-d50'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-xyz-d65 */
  | 'xyz-d65'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-xyz */
  | 'xyz';

export type KeyWord =
  /** https://www.w3.org/TR/css-color-4/#valdef-color-currentcolor */
  | 'currentColor'
  /** https://www.w3.org/TR/css-color-4/#valdef-color-transparent */
  | 'transparent'
  | SharedKeyword;

/**
 * https://developer.mozilla.org/en-US/docs/Web/CSS/named-color
 *
 * https://www.w3.org/TR/css-color-4/#named-colors
 */
export type Named =
  | 'aliceblue'
  | 'antiquewhite'
  | 'aqua'
  | 'aquamarine'
  | 'azure'
  | 'beige'
  | 'bisque'
  | 'black'
  | 'blanchedalmond'
  | 'blue'
  | 'blueviolet'
  | 'brown'
  | 'burlywood'
  | 'cadetblue'
  | 'chartreuse'
  | 'chocolate'
  | 'coral'
  | 'cornflowerblue'
  | 'cornsilk'
  | 'crimson'
  | 'cyan'
  | 'darkblue'
  | 'darkcyan'
  | 'darkgoldenrod'
  | 'darkgray'
  | 'darkgreen'
  | 'darkgrey'
  | 'darkkhaki'
  | 'darkmagenta'
  | 'darkolivegreen'
  | 'darkorange'
  | 'darkorchid'
  | 'darkred'
  | 'darksalmon'
  | 'darkseagreen'
  | 'darkslateblue'
  | 'darkslategray'
  | 'darkslategrey'
  | 'darkturquoise'
  | 'darkviolet'
  | 'deeppink'
  | 'deepskyblue'
  | 'dimgray'
  | 'dimgrey'
  | 'dodgerblue'
  | 'firebrick'
  | 'floralwhite'
  | 'forestgreen'
  | 'fuchsia'
  | 'gainsboro'
  | 'ghostwhite'
  | 'gold'
  | 'goldenrod'
  | 'gray'
  | 'green'
  | 'greenyellow'
  | 'grey'
  | 'honeydew'
  | 'hotpink'
  | 'indianred'
  | 'indigo'
  | 'ivory'
  | 'khaki'
  | 'lavender'
  | 'lavenderblush'
  | 'lawngreen'
  | 'lemonchiffon'
  | 'lightblue'
  | 'lightcoral'
  | 'lightcyan'
  | 'lightgoldenrodyellow'
  | 'lightgray'
  | 'lightgreen'
  | 'lightgrey'
  | 'lightpink'
  | 'lightsalmon'
  | 'lightseagreen'
  | 'lightskyblue'
  | 'lightslategray'
  | 'lightslategrey'
  | 'lightsteelblue'
  | 'lightyellow'
  | 'lime'
  | 'limegreen'
  | 'linen'
  | 'magenta'
  | 'maroon'
  | 'mediumaquamarine'
  | 'mediumblue'
  | 'mediumorchid'
  | 'mediumpurple'
  | 'mediumseagreen'
  | 'mediumslateblue'
  | 'mediumspringgreen'
  | 'mediumturquoise'
  | 'mediumvioletred'
  | 'midnightblue'
  | 'mintcream'
  | 'mistyrose'
  | 'moccasin'
  | 'navajowhite'
  | 'navy'
  | 'oldlace'
  | 'olive'
  | 'olivedrab'
  | 'orange'
  | 'orangered'
  | 'orchid'
  | 'palegoldenrod'
  | 'palegreen'
  | 'paleturquoise'
  | 'palevioletred'
  | 'papayawhip'
  | 'peachpuff'
  | 'peru'
  | 'pink'
  | 'plum'
  | 'powderblue'
  | 'purple'
  | 'rebeccapurple'
  | 'red'
  | 'rosybrown'
  | 'royalblue'
  | 'saddlebrown'
  | 'salmon'
  | 'sandybrown'
  | 'seagreen'
  | 'seashell'
  | 'sienna'
  | 'silver'
  | 'skyblue'
  | 'slateblue'
  | 'slategray'
  | 'slategrey'
  | 'snow'
  | 'springgreen'
  | 'steelblue'
  | 'tan'
  | 'teal'
  | 'thistle'
  | 'tomato'
  | 'turquoise'
  | 'violet'
  | 'wheat'
  | 'white'
  | 'whitesmoke'
  | 'yellow'
  | 'yellowgreen';
