name: Create GitHub Release
description: Create a GitHub release and push tags after a successful release.

inputs:
  files:
    description: 'Files to include in the release'
    default: 'packages/*/dist/**/*'
    required: false
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🔧 Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
      shell: bash

    - name: ⬆️ Push tags to GitHub
      run: git push --follow-tags
      shell: bash

    - name: ✨ Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ inputs.files }}
        generate_release_notes: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
